name: Test the Builds Passing from One step to another

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker -y

    - name: Pull Docker Image
      run: |
        docker pull hello-world

    - name: List Docker Images
      run: docker image ls

  deploy-job:
    runs-on: ubuntu-latest
    steps:
    - name: List docker images before running hello-world
      run: docker image ls
    
    - name: Deplo Docker conatiner
      run: docker run --name hello hello-world
  
    - name: Check Docker container Deployment       
      run: docker ps
