name: Test the Builds Passing from One step to another

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker.io -y
        
  
